services:  
  node:
      build:
        context: .
        args:
          - NODE_ENV=development
      # you can use legacy debug config or new inspect
      # NOTE: if nodemon isn't restarting on changes, you might be on Windows
      # which has trouble seeing file changes, so add -L to use legacy polling
      # https://github.com/remy/nodemon#application-isnt-restarting
      #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
      ports:
        - "3000:3000"
      volumes:
        - .:/opt/node_app/app
        # bind-mounting these two files in will let you add packages during development without rebuilding
        # for example, to add bower to your app while developing, just install it inside the container
        # and then nodemon will restart. Your changes will last until you "docker compose down" and will
        # be saved on host for next build.
        # remember to isntall from the parent directory to the code bind-mount:
        # docker compose exec -w /opt/node_app node npm install --save bower
        - ./package.json:/opt/node_app/package.json
        - ./package-lock.json:/opt/node_app/package-lock.json
  garage-node-a:
    image: dxflrs/garage:v1.1.0
    container_name: garage-node-a
    restart: always
    volumes:
      - garage_data_a:/var/lib/garage/data  # Disque externe monté ici
      - garage_metadata_a:/var/lib/garage/metadata  # Disque externe monté ici
      - ./garage/node-a/garage.toml:/etc/garage.toml
    network_mode: "host"

  garage-node-b:
    image: dxflrs/garage:v1.1.0
    container_name: garage-node-b
    restart: always
    volumes:
      - garage_data_b:/var/lib/garage/data  # Disque externe monté ici
      - garage_metadata_b:/var/lib/garage/metadata  # Disque externe monté ici
      - ./garage/node-b/garage.toml:/etc/garage.toml
    network_mode: "host"

volumes:
  garage_data_a:
  garage_data_b:
  garage_metadata_a:
  garage_metadata_b: